
import java.sql.Date;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cz
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        //Flight
        bookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        statusFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        dropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        
        //Date
        statusDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDates().toArray()));
        waitlistDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDates().toArray()));
        cancelDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDates().toArray()));
        bookingDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDates().toArray()));
        
        //Customer
        bookingCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
        cancelCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
        customerStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        customerPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        customerNameTextfield = new javax.swing.JTextField();
        addCustomerButtom = new javax.swing.JButton();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        addCustomerResults = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        flightNameTextField = new javax.swing.JTextField();
        flightSeatsTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        flightDateTextField = new javax.swing.JTextField();
        addFlightButton = new javax.swing.JButton();
        addDateButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bookingCustomerComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bookingFlightComboBox = new javax.swing.JComboBox<>();
        bookingDateComboBox = new javax.swing.JComboBox<>();
        scrollPane2 = new java.awt.ScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookingResults = new javax.swing.JTextArea();
        bookingButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cancelCustomerComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cancelDateComboBox = new javax.swing.JComboBox<>();
        cancelButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        statusDateComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        statusFlightComboBox = new javax.swing.JComboBox<>();
        checkingStatusButton = new javax.swing.JButton();
        scrollPane3 = new java.awt.ScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        flightStatusandDropFlightResults = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        dropFlightComboBox = new javax.swing.JComboBox<>();
        dropFlightButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        waitlistDateLabel = new javax.swing.JLabel();
        waitlistDateComboBox = new javax.swing.JComboBox<>();
        checkWaitlistButton = new javax.swing.JButton();
        scrollPane4 = new java.awt.ScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        statusResults = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        customerStatusComboBox = new javax.swing.JComboBox<>();
        checkCustomerStatusButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Wawati SC", 1, 64)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 0, 51));
        Title.setText("Flight Scheduler");

        customerPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                customerPaneStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Customer Name:");

        customerNameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTextfieldActionPerformed(evt);
            }
        });

        addCustomerButtom.setText("Add");
        addCustomerButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButtomActionPerformed(evt);
            }
        });

        addCustomerResults.setColumns(20);
        addCustomerResults.setRows(5);
        jScrollPane1.setViewportView(addCustomerResults);

        scrollPane1.add(jScrollPane1);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Flight Name:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Seats:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Date:");

        addFlightButton.setText("Add Flight");
        addFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightButtonActionPerformed(evt);
            }
        });

        addDateButton.setText("Add Date");
        addDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("Example: 2018-08-01");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(flightNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(flightSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(flightDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(addCustomerButtom)
                .addGap(141, 141, 141)
                .addComponent(addFlightButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addDateButton)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(flightNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(flightSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(customerNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(flightDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(6, 6, 6)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCustomerButtom)
                    .addComponent(addDateButton)
                    .addComponent(addFlightButton))
                .addGap(26, 26, 26)
                .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        customerPane.addTab("Customer", jPanel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Customer Name:");

        bookingCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Flight:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Date:");

        bookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bookingDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bookingResults.setColumns(20);
        bookingResults.setRows(5);
        jScrollPane2.setViewportView(bookingResults);

        scrollPane2.add(jScrollPane2);

        bookingButton.setText("Book");
        bookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Customer Name:");

        cancelCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Date:");

        cancelDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookingDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bookingButton)
                        .addGap(128, 128, 128)
                        .addComponent(cancelButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bookingCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bookingFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(127, 127, 127)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(47, Short.MAX_VALUE))
            .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bookingCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cancelCustomerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bookingFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cancelDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bookingDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookingButton)
                    .addComponent(cancelButton))
                .addGap(72, 72, 72)
                .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        );

        customerPane.addTab("Book/Cancel", jPanel2);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Date:");

        statusDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Flight:");

        statusFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        checkingStatusButton.setText("Check");
        checkingStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingStatusButtonActionPerformed(evt);
            }
        });

        flightStatusandDropFlightResults.setColumns(20);
        flightStatusandDropFlightResults.setRows(5);
        jScrollPane3.setViewportView(flightStatusandDropFlightResults);

        scrollPane3.add(jScrollPane3);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Flight Status");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Drop Flight");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Flight:");

        dropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dropFlightButton.setText("Drop Flight");
        dropFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropFlightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(130, 130, 130))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(dropFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(checkingStatusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dropFlightButton)
                .addGap(112, 112, 112))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(statusDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(statusFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(dropFlightComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dropFlightButton)
                    .addComponent(checkingStatusButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(scrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        customerPane.addTab("Flight Status/Drop Flight", jPanel3);

        waitlistDateLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        waitlistDateLabel.setText("Date:");

        waitlistDateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        checkWaitlistButton.setText("Check");
        checkWaitlistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkWaitlistButtonActionPerformed(evt);
            }
        });

        statusResults.setColumns(20);
        statusResults.setRows(5);
        jScrollPane4.setViewportView(statusResults);

        scrollPane4.add(jScrollPane4);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Waitlist Status");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Customer Status");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Customer:");

        customerStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        checkCustomerStatusButton.setText("Check");
        checkCustomerStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCustomerStatusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(waitlistDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waitlistDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkWaitlistButton)
                .addGap(82, 82, 82)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkCustomerStatusButton)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(133, 133, 133))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waitlistDateLabel)
                    .addComponent(waitlistDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkWaitlistButton)
                    .addComponent(jLabel11)
                    .addComponent(customerStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkCustomerStatusButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        customerPane.addTab("Waitlist/Customer Status", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerPane)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkCustomerStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCustomerStatusButtonActionPerformed
        String customer = customerStatusComboBox.getSelectedItem().toString();
        Customer checkBookedCustomer = new Customer();
        Customer checkWaitlistCustomer = new Customer();
        ArrayList<BookingEntry> customerBookedFlight = new ArrayList<>(checkBookedCustomer.getBookedCustomer(customer));
        ArrayList<BookingEntry> customerWaitlistFlight = new ArrayList<>(checkWaitlistCustomer.getWaitlistCustomer(customer));

        if(customerBookedFlight.isEmpty() && customerWaitlistFlight.isEmpty()){
            statusResults.setText("No Customer Status!");
        }
        else{
            statusResults.setText("Customer:\tFlight:\tDate:\tStatus:\n");
            for (int i = 0; i < customerBookedFlight.size(); i++) {
                String flight = customerBookedFlight.get(i).getFlightName();
                Date date = customerBookedFlight.get(i).getDate();
                statusResults.append(customer + "\t" + flight + "\t" + date + "\t" + "Booked\n");
            }
            for (int j = 0; j < customerWaitlistFlight.size(); j++) {
                String waitlistFlight = customerWaitlistFlight.get(j).getFlightName();
                Date waitlistDate = customerWaitlistFlight.get(j).getDate();
                statusResults.append(customer + "\t" + waitlistFlight + "\t" + waitlistDate + "\t" + "Waitlisted\n");
            }
        }
    }//GEN-LAST:event_checkCustomerStatusButtonActionPerformed

    private void checkWaitlistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkWaitlistButtonActionPerformed
        Date day = Date.valueOf(waitlistDateComboBox.getSelectedItem().toString());
        WaitListQueries data = new WaitListQueries();
        ArrayList<WaitList> waitingListNameList = new ArrayList<>(data.getWaitingListCustomers(day));

        if (waitingListNameList.isEmpty()) {
            statusResults.setText("No Waitlist Status");
        } else {
            statusResults.setText("Customer:\tFlight:\tDate:\t\n");
            for (int i = 0; i < waitingListNameList.size(); i++) {
                String flight = waitingListNameList.get(i).getFlightName();
                Date date = waitingListNameList.get(i).getDate();
                String name = waitingListNameList.get(i).getCustomerName();
                statusResults.append(name + "\t" + flight + "\t" + date + "\t\n");
            }
        }
    }//GEN-LAST:event_checkWaitlistButtonActionPerformed

    private void checkingStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingStatusButtonActionPerformed
        Date day = Date.valueOf(statusDateComboBox.getSelectedItem().toString());
        String flightName = statusFlightComboBox.getSelectedItem().toString();
        BookingQueries data = new BookingQueries();
        ArrayList<BookingEntry> bookingNameList = new ArrayList<>(data.getBookedCustomers(flightName, day));

        if (bookingNameList.isEmpty()) {
            flightStatusandDropFlightResults.setText("No Booked Customer!");
        } else {
            flightStatusandDropFlightResults.setText("Customer:\tFlight:\tDate:\t\n");
            for (int i = 0; i < bookingNameList.size(); i++) {
                String flight = bookingNameList.get(i).getFlightName();
                Date date = bookingNameList.get(i).getDate();
                String name = bookingNameList.get(i).getCustomerName();
                flightStatusandDropFlightResults.append(name + "\t" + flight + "\t" + date + "\t\n");
            }
        }
    }//GEN-LAST:event_checkingStatusButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        String customer = cancelCustomerComboBox.getSelectedItem().toString();
        Date date = Date.valueOf(cancelDateComboBox.getSelectedItem().toString());
        
        BookingQueries newBookingListEntry = new BookingQueries();
        BookingQueries cancelCustomer = new BookingQueries();
        ArrayList <String> cancelCustomerFlight = cancelCustomer.getCancelFlights(customer, date);
        cancelCustomer.cancellation(customer, date);
        bookingResults.setText(customer + "'s flight has been cancel successfully on "  + date);
        
        WaitListQueries cancelWaitlist = new WaitListQueries();
        BookingQueries cancelBooking = new BookingQueries();

        bookingResults.append("\n\nWaitlist Customer have been booked!");
        for(int j = 0; j < cancelCustomerFlight.size(); j++)
        {
            if(!cancelWaitlist.isEmpty(cancelCustomerFlight.get(j), date))
            //if(!cancelCustomerFlight.isEmpty())
            {
                
                
                
                
                /*BookingEntry newWaitlistBooking = new BookingEntry(customer);
                newBookingListEntry.addCustomer(newWaitlist.getCustomerName(), newWaitlist.getFlightName(), newWaitlist.getDate()); */

                WaitList returnCustomerBooking = cancelWaitlist.getWaitlistedCustomer(cancelCustomerFlight.get(j), date);
                cancelBooking.addCustomer(returnCustomerBooking.getCustomerName(), cancelCustomerFlight.get(j), date);
                cancelWaitlist.deleteWaitlistCustomer(returnCustomerBooking.getCustomerName(), cancelCustomerFlight.get(j), date);  
                bookingResults.append("\n" + returnCustomerBooking.getCustomerName() + "\t" + cancelCustomerFlight.get(j) + "\t" + date);
            }

            else
            bookingResults.append("\nNo waitlist customer");
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void bookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingButtonActionPerformed

        Date date = Date.valueOf(bookingDateComboBox.getSelectedItem().toString());
        String flightName = bookingFlightComboBox.getSelectedItem().toString();
        String customerName = bookingCustomerComboBox.getSelectedItem().toString();
        BookingEntry newBookingEntry = new BookingEntry(customerName, flightName, date);
        BookingQueries data = new BookingQueries();
        WaitListQueries newWaitingListEntry = new WaitListQueries();
        WaitListQueries waitlistData = new WaitListQueries();

        if (data.checkSeatAvailable(data.getBookingSeats(newBookingEntry.getFlightName(), newBookingEntry.getDate()), data.getFlightseat(newBookingEntry.getFlightName()))) {

            WaitList newWaitlist = new WaitList(customerName,flightName, date);
            newWaitingListEntry.addCustomerToWaitList(newWaitlist.getCustomerName(), newWaitlist.getFlightName(), newWaitlist.getDate());

            ArrayList<WaitList> waitingListNameList = new ArrayList<>(waitlistData.getWaitingListCustomers(date));
            System.out.println(waitingListNameList.get(0));
            bookingResults.setText("The FLIGHT is full, you have been added to the waitlist!\n"
                + "Customer: " + newBookingEntry.getCustomerName() + "\nFlight: " + newBookingEntry.getFlightName() + "\nDate: "
                + newBookingEntry.getDate() + "\nWaitlist Position: " + waitingListNameList.size());
        } else {
            data.addCustomer(newBookingEntry.getCustomerName(), newBookingEntry.getFlightName(),newBookingEntry.getDate());
            bookingResults.setText("You have successfully BOOK the flight!\n"
                + "Customer: " + newBookingEntry.getCustomerName() + "\nFlight: " + newBookingEntry.getFlightName() + "\nDate: "
                + newBookingEntry.getDate());
        }
    }//GEN-LAST:event_bookingButtonActionPerformed

    private void addDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateButtonActionPerformed
        Flight.addFlightDate(Date.valueOf(flightDateTextField.getText()));
        addCustomerResults.setText("Date: " + flightDateTextField.getText() + " has been added");
        bookingDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDates().toArray())); //Update
        cancelDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDates().toArray())); //Update
        waitlistDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDates().toArray())); //Update
        statusDateComboBox.setModel(new javax.swing.DefaultComboBoxModel(Day.getAllDates().toArray())); //Update
    }//GEN-LAST:event_addDateButtonActionPerformed

    private void addFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightButtonActionPerformed
        Flight.addFlight(flightNameTextField.getText(), Integer.valueOf(flightSeatsTextField.getText()));
        addCustomerResults.setText("Flight: " + flightNameTextField.getText() + " has been added.");
        addCustomerResults.append("\nSeats: " + flightSeatsTextField.getText() + " has been added");
        bookingFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray())); //Update
        statusFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray())); //Update
        dropFlightComboBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray())); //Update
        
    }//GEN-LAST:event_addFlightButtonActionPerformed

    private void addCustomerButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButtomActionPerformed
        Customer.addNewCustomer(customerNameTextfield.getText());
        addCustomerResults.setText("Customer Name: " + customerNameTextfield.getText() + " has been added.");
        bookingCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray())); //Update
        cancelCustomerComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray())); //Update
        customerStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray())); //Update
    }//GEN-LAST:event_addCustomerButtomActionPerformed

    private void customerNameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTextfieldActionPerformed

    private void dropFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropFlightButtonActionPerformed
       
    Flight dropFlight = new Flight();
    WaitListQueries dropWaitlist = new WaitListQueries();
    BookingQueries dropBooking = new BookingQueries();
    String flightName = dropFlightComboBox.getSelectedItem().toString();
    Flight.dropFlight(flightName);
    flightStatusandDropFlightResults.setText("Flight: " + flightName + " has been dropped");

    ArrayList <String> getAddedFlight = dropFlight.getAddFlight();
    ArrayList <BookingEntry> getWaitlist = dropWaitlist.getWaitlistCustomerByFlight(flightName);
    ArrayList <BookingEntry> getBooking = dropBooking.getBookingCustomerByFlight(flightName);
    ArrayList <BookingEntry> reBook = new ArrayList<>();

    reBook.addAll(getBooking);
    //reBook.removeAll(getWaitlist);

    //reBook.addAll(getWaitlist); //Why add these? Why not just show that any in getWaitlist could not be rebooked
    //since we always just drop the waitlist

    flightStatusandDropFlightResults.append("\nRebooking Customer: \n");

    dropBooking.removeBooking(flightName); 
    dropWaitlist.removeWaitlist(flightName);

    for(int i =0; i < getWaitlist.size(); i++){
        flightStatusandDropFlightResults.append(getWaitlist.get(i).getCustomerName() + " ----- Dropped\n");
    }

    BookingQueries newBooking = new BookingQueries();
    WaitListQueries newWaitlist = new WaitListQueries();


    for(int i = 0; i < reBook.size(); i++){
    boolean isRebook = true;
    for(int j = 0; j < getAddedFlight.size(); j++){
    //Flight Have No Seat
    if(newBooking.checkSeatAvailable(newBooking.getBookingSeats(getAddedFlight.get(j), reBook.get(i).getDate()), newBooking.getFlightseat(getAddedFlight.get(j)))){
    isRebook = false; 
    }

    //Flight Have Seat
    else{
    isRebook = true;
    newBooking.addCustomer(reBook.get(i).getCustomerName(), getAddedFlight.get(j), reBook.get(i).getDate());
    flightStatusandDropFlightResults.append("\n" + reBook.get(i).getCustomerName() + "\t" + getAddedFlight.get(j) + "\t" + reBook.get(i).getDate());
    flightStatusandDropFlightResults.append(" ----- Rebook Successfully!\n");
    break;
        }
    } 

    //All Flight Have No Seat
    if(!isRebook){
    flightStatusandDropFlightResults.append(reBook.get(i).getCustomerName() + " ----- Dropped\n");
    reBook.remove(i);
    }
} 
        
        
        
        //STEP 1: Find all customers on the flight that was dropped
         
        
        //STEP 2: Find the date for EACH customer on this flight that was booked.
        
        
        //STEP 3: For EACH customer, find a new flight on the day that THE CUSTOMER booked.
        
        
        //STEP 4: Rebook the customer on the new flight on the day the customer wanted to book.
        
        //STEP 5: Drop the flight
        
    }//GEN-LAST:event_dropFlightButtonActionPerformed

    private void customerPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_customerPaneStateChanged
        // TODO add your handling code here:
        
        System.out.println("Update the boxes here.");
    }//GEN-LAST:event_customerPaneStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton addCustomerButtom;
    private javax.swing.JTextArea addCustomerResults;
    private javax.swing.JButton addDateButton;
    private javax.swing.JButton addFlightButton;
    private javax.swing.JButton bookingButton;
    private javax.swing.JComboBox<String> bookingCustomerComboBox;
    private javax.swing.JComboBox<String> bookingDateComboBox;
    private javax.swing.JComboBox<String> bookingFlightComboBox;
    private javax.swing.JTextArea bookingResults;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> cancelCustomerComboBox;
    private javax.swing.JComboBox<String> cancelDateComboBox;
    private javax.swing.JButton checkCustomerStatusButton;
    private javax.swing.JButton checkWaitlistButton;
    private javax.swing.JButton checkingStatusButton;
    private javax.swing.JTextField customerNameTextfield;
    private javax.swing.JTabbedPane customerPane;
    private javax.swing.JComboBox<String> customerStatusComboBox;
    private javax.swing.JButton dropFlightButton;
    private javax.swing.JComboBox<String> dropFlightComboBox;
    private javax.swing.JTextField flightDateTextField;
    private javax.swing.JTextField flightNameTextField;
    private javax.swing.JTextField flightSeatsTextField;
    private javax.swing.JTextArea flightStatusandDropFlightResults;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.ScrollPane scrollPane2;
    private java.awt.ScrollPane scrollPane3;
    private java.awt.ScrollPane scrollPane4;
    private javax.swing.JComboBox<String> statusDateComboBox;
    private javax.swing.JComboBox<String> statusFlightComboBox;
    private javax.swing.JTextArea statusResults;
    private javax.swing.JComboBox<String> waitlistDateComboBox;
    private javax.swing.JLabel waitlistDateLabel;
    // End of variables declaration//GEN-END:variables
}
